name: code formatting

on: pull_request  

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install isort and black
        run: |
          python -m pip install --upgrade pip
          pip install isort black
      - name: Run isort and black
        run: |
          isort  .
          black  .
          
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
            git config --global user.name 'sadakmed' 
            git config --global user.email 'sada_med@protonmail.com' 
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git commit -am "code formatting" || true
            git push
          
          
